#############################################################################
# Makefile for building: fwupdate
# Generated by qmake (3.0) (Qt 5.4.2)
# Project:  fwupdate.pro
# Template: app
# Command: /opt/qt/bin/qmake -spec arm-xilinx-linux-gnueabi-g++ CONFIG+=debug CONFIG+=qml_debug -o Makefile fwupdate.pro
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = arm-xilinx-linux-gnueabi-gcc
CXX           = arm-xilinx-linux-gnueabi-g++
DEFINES       = -DQT_DEPRECATED_WARNINGS -DQT_QML_DEBUG
CFLAGS        = -pipe -g -Wall -W -D_REENTRANT -fPIC $(DEFINES)
CXXFLAGS      = -pipe -g -Wall -W -D_REENTRANT -fPIC $(DEFINES)
INCPATH       = -I. -I/opt/qt/mkspecs/arm-xilinx-linux-gnueabi-g++
QMAKE         = /opt/qt/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = $(COPY_DIR)
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = fwupdate1.0.0
DISTDIR = /home/xiatian/workspace/zynq-can-fwupdate-qt/.tmp/fwupdate1.0.0
LINK          = arm-xilinx-linux-gnueabi-g++
LFLAGS        = 
LIBS          = $(SUBLIBS) -lpthread 
AR            = arm-xilinx-linux-gnueabi-ar cqs
RANLIB        = 
SED           = sed
STRIP         = arm-xilinx-linux-gnueabi-strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		can_app.cpp \
		libsocketcan.c \
		can_if.c \
		gpio.c 
OBJECTS       = main.o \
		can_app.o \
		libsocketcan.o \
		can_if.o \
		gpio.o
DIST          = /opt/qt/mkspecs/features/spec_pre.prf \
		/opt/qt/mkspecs/common/shell-unix.conf \
		/opt/qt/mkspecs/common/unix.conf \
		/opt/qt/mkspecs/common/linux.conf \
		/opt/qt/mkspecs/common/gcc-base.conf \
		/opt/qt/mkspecs/common/gcc-base-unix.conf \
		/opt/qt/mkspecs/common/g++-base.conf \
		/opt/qt/mkspecs/common/g++-unix.conf \
		/opt/qt/mkspecs/qconfig.pri \
		/opt/qt/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/opt/qt/mkspecs/modules/qt_lib_concurrent.pri \
		/opt/qt/mkspecs/modules/qt_lib_concurrent_private.pri \
		/opt/qt/mkspecs/modules/qt_lib_core.pri \
		/opt/qt/mkspecs/modules/qt_lib_core_private.pri \
		/opt/qt/mkspecs/modules/qt_lib_dbus.pri \
		/opt/qt/mkspecs/modules/qt_lib_dbus_private.pri \
		/opt/qt/mkspecs/modules/qt_lib_gui.pri \
		/opt/qt/mkspecs/modules/qt_lib_gui_private.pri \
		/opt/qt/mkspecs/modules/qt_lib_network.pri \
		/opt/qt/mkspecs/modules/qt_lib_network_private.pri \
		/opt/qt/mkspecs/modules/qt_lib_platformsupport_private.pri \
		/opt/qt/mkspecs/modules/qt_lib_printsupport.pri \
		/opt/qt/mkspecs/modules/qt_lib_printsupport_private.pri \
		/opt/qt/mkspecs/modules/qt_lib_script.pri \
		/opt/qt/mkspecs/modules/qt_lib_script_private.pri \
		/opt/qt/mkspecs/modules/qt_lib_scripttools.pri \
		/opt/qt/mkspecs/modules/qt_lib_scripttools_private.pri \
		/opt/qt/mkspecs/modules/qt_lib_sql.pri \
		/opt/qt/mkspecs/modules/qt_lib_sql_private.pri \
		/opt/qt/mkspecs/modules/qt_lib_svg.pri \
		/opt/qt/mkspecs/modules/qt_lib_svg_private.pri \
		/opt/qt/mkspecs/modules/qt_lib_testlib.pri \
		/opt/qt/mkspecs/modules/qt_lib_testlib_private.pri \
		/opt/qt/mkspecs/modules/qt_lib_widgets.pri \
		/opt/qt/mkspecs/modules/qt_lib_widgets_private.pri \
		/opt/qt/mkspecs/modules/qt_lib_xml.pri \
		/opt/qt/mkspecs/modules/qt_lib_xml_private.pri \
		/opt/qt/mkspecs/features/qt_functions.prf \
		/opt/qt/mkspecs/features/qt_config.prf \
		/opt/qt/mkspecs/arm-xilinx-linux-gnueabi-g++/qmake.conf \
		/opt/qt/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/opt/qt/mkspecs/features/exclusive_builds.prf \
		/opt/qt/mkspecs/features/default_pre.prf \
		/opt/qt/mkspecs/features/resolve_config.prf \
		/opt/qt/mkspecs/features/default_post.prf \
		/opt/qt/mkspecs/features/qml_debug.prf \
		/opt/qt/mkspecs/features/warn_on.prf \
		/opt/qt/mkspecs/features/qt.prf \
		/opt/qt/mkspecs/features/unix/thread.prf \
		/opt/qt/mkspecs/features/testcase_targets.prf \
		/opt/qt/mkspecs/features/exceptions.prf \
		/opt/qt/mkspecs/features/yacc.prf \
		/opt/qt/mkspecs/features/lex.prf \
		fwupdate.pro can_app.h \
		libsocketcan.h \
		can_netlink.h \
		can_if.h \
		gpio.h \
		app_include.h main.cpp \
		can_app.cpp \
		libsocketcan.c \
		can_if.c \
		gpio.c
QMAKE_TARGET  = fwupdate
DESTDIR       = #avoid trailing-slash linebreak
TARGET        = fwupdate


first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: fwupdate.pro /opt/qt/mkspecs/arm-xilinx-linux-gnueabi-g++/qmake.conf /opt/qt/mkspecs/features/spec_pre.prf \
		/opt/qt/mkspecs/common/shell-unix.conf \
		/opt/qt/mkspecs/common/unix.conf \
		/opt/qt/mkspecs/common/linux.conf \
		/opt/qt/mkspecs/common/gcc-base.conf \
		/opt/qt/mkspecs/common/gcc-base-unix.conf \
		/opt/qt/mkspecs/common/g++-base.conf \
		/opt/qt/mkspecs/common/g++-unix.conf \
		/opt/qt/mkspecs/qconfig.pri \
		/opt/qt/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/opt/qt/mkspecs/modules/qt_lib_concurrent.pri \
		/opt/qt/mkspecs/modules/qt_lib_concurrent_private.pri \
		/opt/qt/mkspecs/modules/qt_lib_core.pri \
		/opt/qt/mkspecs/modules/qt_lib_core_private.pri \
		/opt/qt/mkspecs/modules/qt_lib_dbus.pri \
		/opt/qt/mkspecs/modules/qt_lib_dbus_private.pri \
		/opt/qt/mkspecs/modules/qt_lib_gui.pri \
		/opt/qt/mkspecs/modules/qt_lib_gui_private.pri \
		/opt/qt/mkspecs/modules/qt_lib_network.pri \
		/opt/qt/mkspecs/modules/qt_lib_network_private.pri \
		/opt/qt/mkspecs/modules/qt_lib_platformsupport_private.pri \
		/opt/qt/mkspecs/modules/qt_lib_printsupport.pri \
		/opt/qt/mkspecs/modules/qt_lib_printsupport_private.pri \
		/opt/qt/mkspecs/modules/qt_lib_script.pri \
		/opt/qt/mkspecs/modules/qt_lib_script_private.pri \
		/opt/qt/mkspecs/modules/qt_lib_scripttools.pri \
		/opt/qt/mkspecs/modules/qt_lib_scripttools_private.pri \
		/opt/qt/mkspecs/modules/qt_lib_sql.pri \
		/opt/qt/mkspecs/modules/qt_lib_sql_private.pri \
		/opt/qt/mkspecs/modules/qt_lib_svg.pri \
		/opt/qt/mkspecs/modules/qt_lib_svg_private.pri \
		/opt/qt/mkspecs/modules/qt_lib_testlib.pri \
		/opt/qt/mkspecs/modules/qt_lib_testlib_private.pri \
		/opt/qt/mkspecs/modules/qt_lib_widgets.pri \
		/opt/qt/mkspecs/modules/qt_lib_widgets_private.pri \
		/opt/qt/mkspecs/modules/qt_lib_xml.pri \
		/opt/qt/mkspecs/modules/qt_lib_xml_private.pri \
		/opt/qt/mkspecs/features/qt_functions.prf \
		/opt/qt/mkspecs/features/qt_config.prf \
		/opt/qt/mkspecs/arm-xilinx-linux-gnueabi-g++/qmake.conf \
		/opt/qt/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/opt/qt/mkspecs/features/exclusive_builds.prf \
		/opt/qt/mkspecs/features/default_pre.prf \
		/opt/qt/mkspecs/features/resolve_config.prf \
		/opt/qt/mkspecs/features/default_post.prf \
		/opt/qt/mkspecs/features/qml_debug.prf \
		/opt/qt/mkspecs/features/warn_on.prf \
		/opt/qt/mkspecs/features/qt.prf \
		/opt/qt/mkspecs/features/unix/thread.prf \
		/opt/qt/mkspecs/features/testcase_targets.prf \
		/opt/qt/mkspecs/features/exceptions.prf \
		/opt/qt/mkspecs/features/yacc.prf \
		/opt/qt/mkspecs/features/lex.prf \
		fwupdate.pro
	$(QMAKE) -spec arm-xilinx-linux-gnueabi-g++ CONFIG+=debug CONFIG+=qml_debug -o Makefile fwupdate.pro
/opt/qt/mkspecs/features/spec_pre.prf:
/opt/qt/mkspecs/common/shell-unix.conf:
/opt/qt/mkspecs/common/unix.conf:
/opt/qt/mkspecs/common/linux.conf:
/opt/qt/mkspecs/common/gcc-base.conf:
/opt/qt/mkspecs/common/gcc-base-unix.conf:
/opt/qt/mkspecs/common/g++-base.conf:
/opt/qt/mkspecs/common/g++-unix.conf:
/opt/qt/mkspecs/qconfig.pri:
/opt/qt/mkspecs/modules/qt_lib_bootstrap_private.pri:
/opt/qt/mkspecs/modules/qt_lib_concurrent.pri:
/opt/qt/mkspecs/modules/qt_lib_concurrent_private.pri:
/opt/qt/mkspecs/modules/qt_lib_core.pri:
/opt/qt/mkspecs/modules/qt_lib_core_private.pri:
/opt/qt/mkspecs/modules/qt_lib_dbus.pri:
/opt/qt/mkspecs/modules/qt_lib_dbus_private.pri:
/opt/qt/mkspecs/modules/qt_lib_gui.pri:
/opt/qt/mkspecs/modules/qt_lib_gui_private.pri:
/opt/qt/mkspecs/modules/qt_lib_network.pri:
/opt/qt/mkspecs/modules/qt_lib_network_private.pri:
/opt/qt/mkspecs/modules/qt_lib_platformsupport_private.pri:
/opt/qt/mkspecs/modules/qt_lib_printsupport.pri:
/opt/qt/mkspecs/modules/qt_lib_printsupport_private.pri:
/opt/qt/mkspecs/modules/qt_lib_script.pri:
/opt/qt/mkspecs/modules/qt_lib_script_private.pri:
/opt/qt/mkspecs/modules/qt_lib_scripttools.pri:
/opt/qt/mkspecs/modules/qt_lib_scripttools_private.pri:
/opt/qt/mkspecs/modules/qt_lib_sql.pri:
/opt/qt/mkspecs/modules/qt_lib_sql_private.pri:
/opt/qt/mkspecs/modules/qt_lib_svg.pri:
/opt/qt/mkspecs/modules/qt_lib_svg_private.pri:
/opt/qt/mkspecs/modules/qt_lib_testlib.pri:
/opt/qt/mkspecs/modules/qt_lib_testlib_private.pri:
/opt/qt/mkspecs/modules/qt_lib_widgets.pri:
/opt/qt/mkspecs/modules/qt_lib_widgets_private.pri:
/opt/qt/mkspecs/modules/qt_lib_xml.pri:
/opt/qt/mkspecs/modules/qt_lib_xml_private.pri:
/opt/qt/mkspecs/features/qt_functions.prf:
/opt/qt/mkspecs/features/qt_config.prf:
/opt/qt/mkspecs/arm-xilinx-linux-gnueabi-g++/qmake.conf:
/opt/qt/mkspecs/features/spec_post.prf:
.qmake.stash:
/opt/qt/mkspecs/features/exclusive_builds.prf:
/opt/qt/mkspecs/features/default_pre.prf:
/opt/qt/mkspecs/features/resolve_config.prf:
/opt/qt/mkspecs/features/default_post.prf:
/opt/qt/mkspecs/features/qml_debug.prf:
/opt/qt/mkspecs/features/warn_on.prf:
/opt/qt/mkspecs/features/qt.prf:
/opt/qt/mkspecs/features/unix/thread.prf:
/opt/qt/mkspecs/features/testcase_targets.prf:
/opt/qt/mkspecs/features/exceptions.prf:
/opt/qt/mkspecs/features/yacc.prf:
/opt/qt/mkspecs/features/lex.prf:
fwupdate.pro:
qmake: FORCE
	@$(QMAKE) -spec arm-xilinx-linux-gnueabi-g++ CONFIG+=debug CONFIG+=qml_debug -o Makefile fwupdate.pro

qmake_all: FORCE


all: Makefile $(TARGET)

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

check: first

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: 

####### Compile

main.o: main.cpp app_include.h \
		can_app.h \
		can_if.h \
		gpio.h \
		libsocketcan.h \
		can_netlink.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

can_app.o: can_app.cpp can_app.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o can_app.o can_app.cpp

libsocketcan.o: libsocketcan.c libsocketcan.h \
		can_netlink.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o libsocketcan.o libsocketcan.c

can_if.o: can_if.c 
	$(CC) -c $(CFLAGS) $(INCPATH) -o can_if.o can_if.c

gpio.o: gpio.c app_include.h \
		can_app.h \
		can_if.h \
		gpio.h \
		libsocketcan.h \
		can_netlink.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o gpio.o gpio.c

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

